function createfigure(X1, Y1, Z1)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  vector of scatter3 x data
%  Y1:  vector of scatter3 y data
%  Z1:  vector of scatter3 z data

%  Auto-generated by MATLAB on 25-Sep-2022 21:38:22

% Create figure
figure1 = figure('NumberTitle','off','Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1);

view(axes1,[5.67908400068395 -5.59412635530974]);
grid(axes1,'on');
hold(axes1,'off');
